!!python/object/new:easydict.EasyDict
state:
  train_2d: false
  no_eval: false
  finetune: true
  partial_train: null
  epochs: 40
  checkpoint_frequency: 10
  batch_size: 8
  accum_steps: 4
  dropout: 0.0
  learning_rate: 0.0002
  weight_decay: 0.01
  lr_decay: 0.99
  lr_scheduler: exponential
  warmup_epochs: 0
  grad_clip_norm: 1.0
  backbone: PoseMamba
  maxlen: 243
  dim_feat: 64
  mlp_ratio: 2
  depth: 10
  att_fuse: true
  input_channels: 2
  use_ssi: false
  use_msm: false
  use_hypergcn: false
  use_gat_head: false
  forward_type: v2_bfs
  data_root: data/motion3d/MB3D_f243s81/
  subset_list: &id001
  - H36M-SH
  dt_file: h36m_sh_conf_cam_source_final.pkl
  clip_len: 243
  data_stride: 81
  rootrel: true
  sample_stride: 1
  num_joints: 17
  no_conf: true
  gt_2d: false
  lambda_3d_velocity: 20.0
  lambda_scale: 0.5
  lambda_lv: 0.0
  lambda_lg: 0.0
  lambda_a: 0.0
  lambda_av: 0.0
  lambda_3dw: 0.0
  lambda_3d: 1.0
  lambda_diff: 0.0
  synthetic: false
  flip: true
  mask_ratio: 0.0
  mask_T_ratio: 0.0
  noise: false
  wandb_project: PoseMamba-bfs-scan
  wandb_entity: msds24068-itu-lahore
  name: exp_ft_bfs_corrected
dictitems:
  train_2d: false
  no_eval: false
  finetune: true
  partial_train: null
  epochs: 40
  checkpoint_frequency: 10
  batch_size: 8
  accum_steps: 4
  dropout: 0.0
  learning_rate: 0.0002
  weight_decay: 0.01
  lr_decay: 0.99
  lr_scheduler: exponential
  warmup_epochs: 0
  grad_clip_norm: 1.0
  backbone: PoseMamba
  maxlen: 243
  dim_feat: 64
  mlp_ratio: 2
  depth: 10
  att_fuse: true
  input_channels: 2
  use_ssi: false
  use_msm: false
  use_hypergcn: false
  use_gat_head: false
  forward_type: v2_bfs
  data_root: data/motion3d/MB3D_f243s81/
  subset_list: *id001
  dt_file: h36m_sh_conf_cam_source_final.pkl
  clip_len: 243
  data_stride: 81
  rootrel: true
  sample_stride: 1
  num_joints: 17
  no_conf: true
  gt_2d: false
  lambda_3d_velocity: 20.0
  lambda_scale: 0.5
  lambda_lv: 0.0
  lambda_lg: 0.0
  lambda_a: 0.0
  lambda_av: 0.0
  lambda_3dw: 0.0
  lambda_3d: 1.0
  lambda_diff: 0.0
  synthetic: false
  flip: true
  mask_ratio: 0.0
  mask_T_ratio: 0.0
  noise: false
  wandb_project: PoseMamba-bfs-scan
  wandb_entity: msds24068-itu-lahore
  name: exp_ft_bfs_corrected
